/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DocumentacaoRouteImport } from './routes/documentacao'
import { Route as EngenhariaRouteImport } from './routes/engenharia'
import { Route as EscadaLc02RouteImport } from './routes/escada-lc02'
import { Route as ExecucaoRouteImport } from './routes/execucao'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as InspecoesRouteImport } from './routes/inspecoes'
import { Route as LevantamentosRouteImport } from './routes/levantamentos'
import { Route as Mapas3dRouteImport } from './routes/mapas-3d'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as Mapas3dTrevisanRouteImport } from './routes/mapas-3d_.trevisan'
import { Route as Mapas3dUnidadesRouteImport } from './routes/mapas-3d_.unidades'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentacaoRoute = DocumentacaoRouteImport.update({
  id: '/documentacao',
  path: '/documentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EngenhariaRoute = EngenhariaRouteImport.update({
  id: '/engenharia',
  path: '/engenharia',
  getParentRoute: () => rootRouteImport,
} as any)
const EscadaLc02Route = EscadaLc02RouteImport.update({
  id: '/escada-lc02',
  path: '/escada-lc02',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecucaoRoute = ExecucaoRouteImport.update({
  id: '/execucao',
  path: '/execucao',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecoesRoute = InspecoesRouteImport.update({
  id: '/inspecoes',
  path: '/inspecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LevantamentosRoute = LevantamentosRouteImport.update({
  id: '/levantamentos',
  path: '/levantamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const Mapas3dRoute = Mapas3dRouteImport.update({
  id: '/mapas-3d',
  path: '/mapas-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const Mapas3dTrevisanRoute = Mapas3dTrevisanRouteImport.update({
  id: '/mapas-3d_/trevisan',
  path: '/mapas-3d/trevisan',
  getParentRoute: () => rootRouteImport,
} as any)
const Mapas3dUnidadesRoute = Mapas3dUnidadesRouteImport.update({
  id: '/mapas-3d_/unidades',
  path: '/mapas-3d/unidades',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/comercial': typeof ComercialRoute
  '/compras': typeof ComprasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentacao': typeof DocumentacaoRoute
  '/engenharia': typeof EngenhariaRoute
  '/escada-lc02': typeof EscadaLc02Route
  '/execucao': typeof ExecucaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/inspecoes': typeof InspecoesRoute
  '/levantamentos': typeof LevantamentosRoute
  '/mapas-3d': typeof Mapas3dRoute
  '/produtos': typeof ProdutosRoute
  '/projetos': typeof ProjetosRoute
  '/relatorios': typeof RelatoriosRoute
  '/mapas-3d/trevisan': typeof Mapas3dTrevisanRoute
  '/mapas-3d/unidades': typeof Mapas3dUnidadesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/comercial': typeof ComercialRoute
  '/compras': typeof ComprasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentacao': typeof DocumentacaoRoute
  '/engenharia': typeof EngenhariaRoute
  '/escada-lc02': typeof EscadaLc02Route
  '/execucao': typeof ExecucaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/inspecoes': typeof InspecoesRoute
  '/levantamentos': typeof LevantamentosRoute
  '/mapas-3d': typeof Mapas3dRoute
  '/produtos': typeof ProdutosRoute
  '/projetos': typeof ProjetosRoute
  '/relatorios': typeof RelatoriosRoute
  '/mapas-3d/trevisan': typeof Mapas3dTrevisanRoute
  '/mapas-3d/unidades': typeof Mapas3dUnidadesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/comercial': typeof ComercialRoute
  '/compras': typeof ComprasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentacao': typeof DocumentacaoRoute
  '/engenharia': typeof EngenhariaRoute
  '/escada-lc02': typeof EscadaLc02Route
  '/execucao': typeof ExecucaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/inspecoes': typeof InspecoesRoute
  '/levantamentos': typeof LevantamentosRoute
  '/mapas-3d': typeof Mapas3dRoute
  '/produtos': typeof ProdutosRoute
  '/projetos': typeof ProjetosRoute
  '/relatorios': typeof RelatoriosRoute
  '/mapas-3d_/trevisan': typeof Mapas3dTrevisanRoute
  '/mapas-3d_/unidades': typeof Mapas3dUnidadesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/comercial'
    | '/compras'
    | '/configuracoes'
    | '/documentacao'
    | '/engenharia'
    | '/escada-lc02'
    | '/execucao'
    | '/financeiro'
    | '/inspecoes'
    | '/levantamentos'
    | '/mapas-3d'
    | '/produtos'
    | '/projetos'
    | '/relatorios'
    | '/mapas-3d/trevisan'
    | '/mapas-3d/unidades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/comercial'
    | '/compras'
    | '/configuracoes'
    | '/documentacao'
    | '/engenharia'
    | '/escada-lc02'
    | '/execucao'
    | '/financeiro'
    | '/inspecoes'
    | '/levantamentos'
    | '/mapas-3d'
    | '/produtos'
    | '/projetos'
    | '/relatorios'
    | '/mapas-3d/trevisan'
    | '/mapas-3d/unidades'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/comercial'
    | '/compras'
    | '/configuracoes'
    | '/documentacao'
    | '/engenharia'
    | '/escada-lc02'
    | '/execucao'
    | '/financeiro'
    | '/inspecoes'
    | '/levantamentos'
    | '/mapas-3d'
    | '/produtos'
    | '/projetos'
    | '/relatorios'
    | '/mapas-3d_/trevisan'
    | '/mapas-3d_/unidades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ComercialRoute: typeof ComercialRoute
  ComprasRoute: typeof ComprasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DocumentacaoRoute: typeof DocumentacaoRoute
  EngenhariaRoute: typeof EngenhariaRoute
  EscadaLc02Route: typeof EscadaLc02Route
  ExecucaoRoute: typeof ExecucaoRoute
  FinanceiroRoute: typeof FinanceiroRoute
  InspecoesRoute: typeof InspecoesRoute
  LevantamentosRoute: typeof LevantamentosRoute
  Mapas3dRoute: typeof Mapas3dRoute
  ProdutosRoute: typeof ProdutosRoute
  ProjetosRoute: typeof ProjetosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  Mapas3dTrevisanRoute: typeof Mapas3dTrevisanRoute
  Mapas3dUnidadesRoute: typeof Mapas3dUnidadesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentacao': {
      id: '/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof DocumentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engenharia': {
      id: '/engenharia'
      path: '/engenharia'
      fullPath: '/engenharia'
      preLoaderRoute: typeof EngenhariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escada-lc02': {
      id: '/escada-lc02'
      path: '/escada-lc02'
      fullPath: '/escada-lc02'
      preLoaderRoute: typeof EscadaLc02RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execucao': {
      id: '/execucao'
      path: '/execucao'
      fullPath: '/execucao'
      preLoaderRoute: typeof ExecucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecoes': {
      id: '/inspecoes'
      path: '/inspecoes'
      fullPath: '/inspecoes'
      preLoaderRoute: typeof InspecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levantamentos': {
      id: '/levantamentos'
      path: '/levantamentos'
      fullPath: '/levantamentos'
      preLoaderRoute: typeof LevantamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-3d': {
      id: '/mapas-3d'
      path: '/mapas-3d'
      fullPath: '/mapas-3d'
      preLoaderRoute: typeof Mapas3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-3d_/trevisan': {
      id: '/mapas-3d_/trevisan'
      path: '/mapas-3d/trevisan'
      fullPath: '/mapas-3d/trevisan'
      preLoaderRoute: typeof Mapas3dTrevisanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-3d_/unidades': {
      id: '/mapas-3d_/unidades'
      path: '/mapas-3d/unidades'
      fullPath: '/mapas-3d/unidades'
      preLoaderRoute: typeof Mapas3dUnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ComercialRoute: ComercialRoute,
  ComprasRoute: ComprasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DocumentacaoRoute: DocumentacaoRoute,
  EngenhariaRoute: EngenhariaRoute,
  EscadaLc02Route: EscadaLc02Route,
  ExecucaoRoute: ExecucaoRoute,
  FinanceiroRoute: FinanceiroRoute,
  InspecoesRoute: InspecoesRoute,
  LevantamentosRoute: LevantamentosRoute,
  Mapas3dRoute: Mapas3dRoute,
  ProdutosRoute: ProdutosRoute,
  ProjetosRoute: ProjetosRoute,
  RelatoriosRoute: RelatoriosRoute,
  Mapas3dTrevisanRoute: Mapas3dTrevisanRoute,
  Mapas3dUnidadesRoute: Mapas3dUnidadesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
